# application.yml
server:
  port: 8080 # 默认端口

spring:
  profiles:
    active: dev

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# MyBatis 配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com # OSS 外网访问域名
    access-key-id: your-access-key-id       # AccessKey ID
    access-key-secret: your-access-key-secret # AccessKey Secret
    bucket-name: your-bucket-name           # Bucket 名称

# JWT 配置
chatroom:
  jwt:
    admin-secret-key: fsuit_servie_admin
    admin-ttl: 604800000
    admin-token-name: Authorization
    user-secret-key: fsuit_servie_user
    user-ttl: 604800000
    user-token-name: Authorization
jasypt:
  encryptor:
    password: fsuit_servie_chat
