# application.yml
server:
  port: 8080 # 默认端口

spring:
  profiles:
    active: prod # 【关键】默认激活 dev 环境（本地开发）

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# MyBatis 配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml



# JWT 配置
chatroom:
  jwt:
    admin-secret-key: ENC(IA94BMT6mhxoKzquh+anPottQYpLPDu1374cv0Lr8OE=)
    admin-ttl: 604800000
    admin-token-name: Authorization
    user-secret-key: ENC(MMuZPeE0CDKwaS4KI1Hs8enESr47X9KO7nnJnm098ik=)
    user-ttl: 604800000
    user-token-name: Authorization
jasypt:
  encryptor:
    password: fsuit_servie_chat
